The wise Beaver's big dam of logs: 
---------------------------------------
__main__: Sent message: LoaderTaskType.LOAD
---------------------------------------
BlackBox-2: Start of service
---------------------------------------
Loader: Start of service
---------------------------------------
Loader: Recieved message: LoaderTaskType.LOAD
---------------------------------------
Loading 5 more images
---------------------------------------
    - Loaded ../img/test/1.jpg
---------------------------------------
Loader: Sent message: TaskType.PROCESS
---------------------------------------
    - Loaded ../img/test/2.jpg
---------------------------------------
BlackBox-2: Recieved message: TaskType.PROCESS
---------------------------------------
Loader: Sent message: TaskType.PROCESS
---------------------------------------
    - Loaded ../img/test/3.jpg
---------------------------------------
Loader: Sent message: TaskType.PROCESS
---------------------------------------
    - Loaded ../img/test/4.jpg
---------------------------------------
Loader: Sent message: TaskType.PROCESS
---------------------------------------
Loader: Sent message: LoaderAnswerType.NOMORE
---------------------------------------
__main__: Recieved message: LoaderAnswerType.NOMORE
---------------------------------------
Loader: Sent message: LoaderAnswerType.LOADDONE
---------------------------------------
__main__: Sent message: LoaderTaskType.TERMINATE
---------------------------------------
Loader: Recieved message: LoaderTaskType.TERMINATE
---------------------------------------
__main__: Recieved message: LoaderAnswerType.LOADDONE
---------------------------------------
Loader: Sent message: LoaderAnswerType.END
---------------------------------------
Loader: End of service
---------------------------------------
__main__: Recieved message: LoaderAnswerType.END
---------------------------------------
BlackBox-2: New data written in the test output file.
---------------------------------------
BlackBox-2: Recieved message: TaskType.PROCESS
---------------------------------------
BlackBox-2: New data written in the test output file.
---------------------------------------
BlackBox-2: Recieved message: TaskType.PROCESS
---------------------------------------
BlackBox-2: New data written in the test output file.
---------------------------------------
BlackBox-2: Recieved message: TaskType.PROCESS
---------------------------------------
__main__: Sent message: TaskType.END
---------------------------------------
BlackBox-2: New data written in the test output file.
---------------------------------------
BlackBox-2: Recieved message: TaskType.END
---------------------------------------
__main__: End of service
---------------------------------------
BlackBox-2: Sent message: AnswerType.BOXENDSERVICE
---------------------------------------
BlackBox-2: End of service
---------------------------------------
BlackBox-2 encountered an error, and stopped its execution. See the error below: 

---------------------------------------
Traceback (most recent call last):
  File "C:\Users\Esteban\Documents\GitHub\projet-i3-sneaker\src\BlackBox.py", line 77, in run
    self.compute(nextTask.img, nextTask.imgPath, nextTask.imgPathInCache, nextTask.tfImg, modelShoeDetector)
  File "C:\Users\Esteban\Documents\GitHub\projet-i3-sneaker\src\BlackBox.py", line 167, in compute
    Herald.printResults(dataShoesJson)
  File "C:\Users\Esteban\Documents\GitHub\projet-i3-sneaker\src\utilities\Herald.py", line 87, in printResults
    pprint(Fore.YELLOW+Style.BRIGHT+str(results)+Style.RESET_ALL)
TypeError: 'module' object is not callable

---------------------------------------
No blackboxes are running. Politely stopping the program.
---------------------------------------
BlackBox-2 encountered an error, and stopped its execution. See the error below: 

---------------------------------------
Traceback (most recent call last):
  File "C:\Users\Esteban\Documents\GitHub\projet-i3-sneaker\src\BlackBox.py", line 77, in run
    self.compute(nextTask.img, nextTask.imgPath, nextTask.imgPathInCache, nextTask.tfImg, modelShoeDetector)
  File "C:\Users\Esteban\Documents\GitHub\projet-i3-sneaker\src\BlackBox.py", line 167, in compute
    Herald.printResults(dataShoesJson)
  File "C:\Users\Esteban\Documents\GitHub\projet-i3-sneaker\src\utilities\Herald.py", line 89, in printResults
    msg += Herald.getPrintElement(key, results[key])
TypeError: string indices must be integers

---------------------------------------
No blackboxes are running. Politely stopping the program.
---------------------------------------
BlackBox-2 encountered an error, and stopped its execution. See the error below: 

---------------------------------------
Traceback (most recent call last):
  File "C:\Users\Esteban\Documents\GitHub\projet-i3-sneaker\src\BlackBox.py", line 77, in run
    self.compute(nextTask.img, nextTask.imgPath, nextTask.imgPathInCache, nextTask.tfImg, modelShoeDetector)
  File "C:\Users\Esteban\Documents\GitHub\projet-i3-sneaker\src\BlackBox.py", line 167, in compute
    Herald.printResults(dataShoesJson)
  File "C:\Users\Esteban\Documents\GitHub\projet-i3-sneaker\src\utilities\Herald.py", line 90, in printResults
    msg += Herald.getPrintElement(key, results[key])
TypeError: string indices must be integers

---------------------------------------
No blackboxes are running. Politely stopping the program.
---------------------------------------
BlackBox-2 encountered an error, and stopped its execution. See the error below: 

---------------------------------------
Traceback (most recent call last):
  File "C:\Users\Esteban\Documents\GitHub\projet-i3-sneaker\src\BlackBox.py", line 77, in run
    self.compute(nextTask.img, nextTask.imgPath, nextTask.imgPathInCache, nextTask.tfImg, modelShoeDetector)
  File "C:\Users\Esteban\Documents\GitHub\projet-i3-sneaker\src\BlackBox.py", line 167, in compute
    Herald.printResults(dataShoesJson)
  File "C:\Users\Esteban\Documents\GitHub\projet-i3-sneaker\src\utilities\Herald.py", line 91, in printResults
    msg += Herald.getPrintElement(key, results[key])
TypeError: string indices must be integers

---------------------------------------
No blackboxes are running. Politely stopping the program.
---------------------------------------
BlackBox-2 encountered an error, and stopped its execution. See the error below: 

---------------------------------------
Traceback (most recent call last):
  File "C:\Users\Esteban\Documents\GitHub\projet-i3-sneaker\src\BlackBox.py", line 77, in run
    self.compute(nextTask.img, nextTask.imgPath, nextTask.imgPathInCache, nextTask.tfImg, modelShoeDetector)
  File "C:\Users\Esteban\Documents\GitHub\projet-i3-sneaker\src\BlackBox.py", line 167, in compute
    Herald.printResults(dataShoesJson)
  File "C:\Users\Esteban\Documents\GitHub\projet-i3-sneaker\src\utilities\Herald.py", line 91, in printResults
    msg += Herald.getPrintElement(key, results[key])
TypeError: string indices must be integers

---------------------------------------
No blackboxes are running. Politely stopping the program.
---------------------------------------
BlackBox-2 encountered an error, and stopped its execution. See the error below: 

---------------------------------------
Traceback (most recent call last):
  File "C:\Users\Esteban\Documents\GitHub\projet-i3-sneaker\src\BlackBox.py", line 77, in run
    self.compute(nextTask.img, nextTask.imgPath, nextTask.imgPathInCache, nextTask.tfImg, modelShoeDetector)
  File "C:\Users\Esteban\Documents\GitHub\projet-i3-sneaker\src\BlackBox.py", line 167, in compute
    Herald.printResults(dataShoes)
  File "C:\Users\Esteban\Documents\GitHub\projet-i3-sneaker\src\utilities\Herald.py", line 90, in printResults
    msg += Herald.getPrintElement(key, results[key], 1)
  File "C:\Users\Esteban\Documents\GitHub\projet-i3-sneaker\src\utilities\Herald.py", line 95, in getPrintElement
    for i in indent: indentStr += '    '
TypeError: 'int' object is not iterable

---------------------------------------
No blackboxes are running. Politely stopping the program.
---------------------------------------
BlackBox-2 encountered an error, and stopped its execution. See the error below: 

---------------------------------------
Traceback (most recent call last):
  File "C:\Users\Esteban\Documents\GitHub\projet-i3-sneaker\src\BlackBox.py", line 77, in run
    self.compute(nextTask.img, nextTask.imgPath, nextTask.imgPathInCache, nextTask.tfImg, modelShoeDetector)
  File "C:\Users\Esteban\Documents\GitHub\projet-i3-sneaker\src\BlackBox.py", line 167, in compute
    Herald.printResults(dataShoes)
  File "C:\Users\Esteban\Documents\GitHub\projet-i3-sneaker\src\utilities\Herald.py", line 90, in printResults
    msg += Herald.getPrintElement(key, results[key], 1)
  File "C:\Users\Esteban\Documents\GitHub\projet-i3-sneaker\src\utilities\Herald.py", line 101, in getPrintElement
    msg += Herald.getPrintElement(key, element[key])
TypeError: getPrintElement() missing 1 required positional argument: 'indent'

---------------------------------------
No blackboxes are running. Politely stopping the program.
---------------------------------------
BlackBox-2 encountered an error, and stopped its execution. See the error below: 

---------------------------------------
Traceback (most recent call last):
  File "C:\Users\Esteban\Documents\GitHub\projet-i3-sneaker\src\BlackBox.py", line 80, in run
    self.compute(nextTask.img, nextTask.imgPath, nextTask.imgPathInCache, nextTask.tfImg, modelShoeDetector)
  File "C:\Users\Esteban\Documents\GitHub\projet-i3-sneaker\src\BlackBox.py", line 146, in compute
    Writer.writeDataToTempFile(self.name, dataShoes)
  File "C:\Users\Esteban\Documents\GitHub\projet-i3-sneaker\src\interface\Writer.py", line 16, in writeDataToTempFile
    outputFilePath = (os.join(tempDir, procName+'.json'))
AttributeError: module 'os' has no attribute 'join'

---------------------------------------
BlackBox-2 encountered an error, and stopped its execution. See the error below: 

---------------------------------------
Traceback (most recent call last):
  File "C:\Users\Esteban\Documents\GitHub\projet-i3-sneaker\src\BlackBox.py", line 80, in run
    self.compute(nextTask.img, nextTask.imgPath, nextTask.imgPathInCache, nextTask.tfImg, modelShoeDetector)
  File "C:\Users\Esteban\Documents\GitHub\projet-i3-sneaker\src\BlackBox.py", line 146, in compute
    Writer.writeDataToTempFile(self.name, dataShoes)
  File "C:\Users\Esteban\Documents\GitHub\projet-i3-sneaker\src\interface\Writer.py", line 18, in writeDataToTempFile
    with open(outputFilePath, 'a') as f:
FileNotFoundError: [Errno 2] No such file or directory: '../out/temp\\BlackBox-2.json'

---------------------------------------
BlackBox-2 encountered an error, and stopped its execution. See the error below: 

---------------------------------------
Traceback (most recent call last):
  File "C:\Users\Esteban\Documents\GitHub\projet-i3-sneaker\src\BlackBox.py", line 80, in run
    self.compute(nextTask.img, nextTask.imgPath, nextTask.imgPathInCache, nextTask.tfImg, modelShoeDetector)
  File "C:\Users\Esteban\Documents\GitHub\projet-i3-sneaker\src\BlackBox.py", line 146, in compute
    Writer.writeDataToTempFile(self.name, dataShoes)
  File "C:\Users\Esteban\Documents\GitHub\projet-i3-sneaker\src\interface\Writer.py", line 19, in writeDataToTempFile
    with open(outputFilePath, 'a') as f:
FileNotFoundError: [Errno 2] No such file or directory: '../out/temp\\BlackBox-2.json'

---------------------------------------
BlackBox-4 encountered an error, and stopped its execution. See the error below: 

---------------------------------------
Traceback (most recent call last):
  File "C:\Users\Esteban\Documents\GitHub\projet-i3-sneaker\src\BlackBox.py", line 80, in run
    self.compute(nextTask.img, nextTask.imgPath, nextTask.imgPathInCache, nextTask.tfImg, modelShoeDetector)
  File "C:\Users\Esteban\Documents\GitHub\projet-i3-sneaker\src\BlackBox.py", line 146, in compute
    Writer.writeDataToTempFile(self.name, dataShoes)
  File "C:\Users\Esteban\Documents\GitHub\projet-i3-sneaker\src\interface\Writer.py", line 19, in writeDataToTempFile
    with open(outputFilePath, 'a') as f:
FileNotFoundError: [Errno 2] No such file or directory: '../out/temp/BlackBox-4.json'

---------------------------------------
BlackBox-2 encountered an error, and stopped its execution. See the error below: 

---------------------------------------
Traceback (most recent call last):
  File "C:\Users\Esteban\Documents\GitHub\projet-i3-sneaker\src\BlackBox.py", line 80, in run
    self.compute(nextTask.img, nextTask.imgPath, nextTask.imgPathInCache, nextTask.tfImg, modelShoeDetector)
  File "C:\Users\Esteban\Documents\GitHub\projet-i3-sneaker\src\BlackBox.py", line 146, in compute
    Writer.writeDataToTempFile(self.name, dataShoes)
  File "C:\Users\Esteban\Documents\GitHub\projet-i3-sneaker\src\interface\Writer.py", line 19, in writeDataToTempFile
    with open(outputFilePath, 'a') as f:
FileNotFoundError: [Errno 2] No such file or directory: '../out/temp/BlackBox-2.json'

---------------------------------------
BlackBox-3 encountered an error, and stopped its execution. See the error below: 

---------------------------------------
Traceback (most recent call last):
  File "C:\Users\Esteban\Documents\GitHub\projet-i3-sneaker\src\BlackBox.py", line 80, in run
    self.compute(nextTask.img, nextTask.imgPath, nextTask.imgPathInCache, nextTask.tfImg, modelShoeDetector)
  File "C:\Users\Esteban\Documents\GitHub\projet-i3-sneaker\src\BlackBox.py", line 146, in compute
    Writer.writeDataToTempFile(self.name, dataShoes)
  File "C:\Users\Esteban\Documents\GitHub\projet-i3-sneaker\src\interface\Writer.py", line 19, in writeDataToTempFile
    with open(outputFilePath, 'a') as f:
FileNotFoundError: [Errno 2] No such file or directory: '../out/temp/BlackBox-3.json'

---------------------------------------
No blackboxes are running. Politely stopping the program.
---------------------------------------
BlackBox-2 encountered an error, and stopped its execution. See the error below: 

---------------------------------------
Traceback (most recent call last):
  File "C:\Users\Esteban\Documents\GitHub\projet-i3-sneaker\src\BlackBox.py", line 80, in run
    self.compute(nextTask.img, nextTask.imgPath, nextTask.imgPathInCache, nextTask.tfImg, modelShoeDetector)
  File "C:\Users\Esteban\Documents\GitHub\projet-i3-sneaker\src\BlackBox.py", line 119, in compute
    (mainColor, secondaryColor) = ColorDetector.detection(
  File "C:\Users\Esteban\Documents\GitHub\projet-i3-sneaker\src\blackBoxModules\colorDetector\ColorDetector.py", line 320, in detection
    ColorDetector.persistanceColor(res)
  File "C:\Users\Esteban\Documents\GitHub\projet-i3-sneaker\src\blackBoxModules\colorDetector\ColorDetector.py", line 249, in persistanceColor
    deuxiemeElem = str([*keys][1])
IndexError: list index out of range

---------------------------------------
BlackBox-4 encountered an error, and stopped its execution. See the error below: 

---------------------------------------
Traceback (most recent call last):
  File "C:\Users\Esteban\Documents\GitHub\projet-i3-sneaker\src\BlackBox.py", line 80, in run
    self.compute(nextTask.img, nextTask.imgPath, nextTask.imgPathInCache, nextTask.tfImg, modelShoeDetector)
  File "C:\Users\Esteban\Documents\GitHub\projet-i3-sneaker\src\BlackBox.py", line 119, in compute
    (mainColor, secondaryColor) = ColorDetector.detection(
  File "C:\Users\Esteban\Documents\GitHub\projet-i3-sneaker\src\blackBoxModules\colorDetector\ColorDetector.py", line 320, in detection
    ColorDetector.persistanceColor(res)
  File "C:\Users\Esteban\Documents\GitHub\projet-i3-sneaker\src\blackBoxModules\colorDetector\ColorDetector.py", line 249, in persistanceColor
    deuxiemeElem = str([*keys][1])
IndexError: list index out of range

---------------------------------------
BlackBox-4 encountered an error, and stopped its execution. See the error below: 

---------------------------------------
Traceback (most recent call last):
  File "C:\Users\Esteban\Documents\GitHub\projet-i3-sneaker\src\BlackBox.py", line 80, in run
    self.compute(nextTask.img, nextTask.imgPath, nextTask.imgPathInCache, nextTask.tfImg, modelShoeDetector)
  File "C:\Users\Esteban\Documents\GitHub\projet-i3-sneaker\src\BlackBox.py", line 119, in compute
    (mainColor, secondaryColor) = ColorDetector.detection(
  File "C:\Users\Esteban\Documents\GitHub\projet-i3-sneaker\src\blackBoxModules\colorDetector\ColorDetector.py", line 320, in detection
    ColorDetector.persistanceColor(res)
  File "C:\Users\Esteban\Documents\GitHub\projet-i3-sneaker\src\blackBoxModules\colorDetector\ColorDetector.py", line 249, in persistanceColor
    deuxiemeElem = str([*keys][1])
IndexError: list index out of range

---------------------------------------
BlackBox-2 encountered an error, and stopped its execution. See the error below: 

---------------------------------------
Traceback (most recent call last):
  File "C:\Users\Esteban\Documents\GitHub\projet-i3-sneaker\src\BlackBox.py", line 80, in run
    self.compute(nextTask.img, nextTask.imgPath, nextTask.imgPathInCache, nextTask.tfImg, modelShoeDetector)
  File "C:\Users\Esteban\Documents\GitHub\projet-i3-sneaker\src\BlackBox.py", line 119, in compute
    (mainColor, secondaryColor) = ColorDetector.detection(
  File "C:\Users\Esteban\Documents\GitHub\projet-i3-sneaker\src\blackBoxModules\colorDetector\ColorDetector.py", line 320, in detection
    ColorDetector.persistanceColor(res)
  File "C:\Users\Esteban\Documents\GitHub\projet-i3-sneaker\src\blackBoxModules\colorDetector\ColorDetector.py", line 249, in persistanceColor
    deuxiemeElem = str([*keys][1])
IndexError: list index out of range

---------------------------------------
BlackBox-3 encountered an error, and stopped its execution. See the error below: 

---------------------------------------
Traceback (most recent call last):
  File "C:\Users\Esteban\Documents\GitHub\projet-i3-sneaker\src\BlackBox.py", line 80, in run
    self.compute(nextTask.img, nextTask.imgPath, nextTask.imgPathInCache, nextTask.tfImg, modelShoeDetector)
  File "C:\Users\Esteban\Documents\GitHub\projet-i3-sneaker\src\BlackBox.py", line 119, in compute
    (mainColor, secondaryColor) = ColorDetector.detection(
  File "C:\Users\Esteban\Documents\GitHub\projet-i3-sneaker\src\blackBoxModules\colorDetector\ColorDetector.py", line 320, in detection
    ColorDetector.persistanceColor(res)
  File "C:\Users\Esteban\Documents\GitHub\projet-i3-sneaker\src\blackBoxModules\colorDetector\ColorDetector.py", line 249, in persistanceColor
    deuxiemeElem = str([*keys][1])
IndexError: list index out of range

---------------------------------------
No blackboxes are running. Politely stopping the program.
---------------------------------------
BlackBox-2 encountered an error, and stopped its execution. See the error below: 

---------------------------------------
Traceback (most recent call last):
  File "D:\Python projects\projet-i3-sneaker\src\BlackBox.py", line 80, in run
    self.compute(nextTask.img, nextTask.imgPath, nextTask.imgPathInCache, nextTask.tfImg, modelShoeDetector)
  File "D:\Python projects\projet-i3-sneaker\src\BlackBox.py", line 147, in compute
    Writer.writeDataToTempFile(self.name, dataShoes)
UnboundLocalError: local variable 'dataShoes' referenced before assignment

---------------------------------------
BlackBox-3 encountered an error, and stopped its execution. See the error below: 

---------------------------------------
Traceback (most recent call last):
  File "D:\Python projects\projet-i3-sneaker\src\BlackBox.py", line 80, in run
    self.compute(nextTask.img, nextTask.imgPath, nextTask.imgPathInCache, nextTask.tfImg, modelShoeDetector)
  File "D:\Python projects\projet-i3-sneaker\src\BlackBox.py", line 147, in compute
    <<<<<<< HEAD
UnboundLocalError: local variable 'dataShoes' referenced before assignment

---------------------------------------
BlackBox-5 encountered an error, and stopped its execution. See the error below: 

---------------------------------------
Traceback (most recent call last):
  File "D:\Python projects\projet-i3-sneaker\src\BlackBox.py", line 80, in run
    self.compute(nextTask.img, nextTask.imgPath, nextTask.imgPathInCache, nextTask.tfImg, modelShoeDetector)
  File "D:\Python projects\projet-i3-sneaker\src\BlackBox.py", line 122, in compute
    (mainColor, secondaryColor) = ColorDetector.detection(
  File "D:\Python projects\projet-i3-sneaker\src\blackBoxModules\colorDetector\ColorDetector.py", line 320, in detection
    ColorDetector.persistanceColor(res)
  File "D:\Python projects\projet-i3-sneaker\src\blackBoxModules\colorDetector\ColorDetector.py", line 249, in persistanceColor
    deuxiemeElem = str([*keys][1])
IndexError: list index out of range

---------------------------------------
BlackBox-3 encountered an error, and stopped its execution. See the error below: 

---------------------------------------
Traceback (most recent call last):
  File "D:\Python projects\projet-i3-sneaker\src\BlackBox.py", line 80, in run
    self.compute(nextTask.img, nextTask.imgPath, nextTask.imgPathInCache, nextTask.tfImg, modelShoeDetector)
  File "D:\Python projects\projet-i3-sneaker\src\BlackBox.py", line 124, in compute
    (mainColor, secondaryColor) = ColorDetector.detection(
  File "D:\Python projects\projet-i3-sneaker\src\blackBoxModules\colorDetector\ColorDetector.py", line 321, in detection
    ColorDetector.persistanceColor(res)
  File "D:\Python projects\projet-i3-sneaker\src\blackBoxModules\colorDetector\ColorDetector.py", line 250, in persistanceColor
    deuxiemeElem = str([*keys][1])
IndexError: list index out of range

---------------------------------------
BlackBox-2 encountered an error, and stopped its execution. See the error below: 

---------------------------------------
Traceback (most recent call last):
  File "D:\Python projects\projet-i3-sneaker\src\BlackBox.py", line 80, in run
    self.compute(nextTask.img, nextTask.imgPath, nextTask.imgPathInCache, nextTask.tfImg, modelShoeDetector)
  File "D:\Python projects\projet-i3-sneaker\src\BlackBox.py", line 124, in compute
    (mainColor, secondaryColor) = ColorDetector.detection(
  File "D:\Python projects\projet-i3-sneaker\src\blackBoxModules\colorDetector\ColorDetector.py", line 321, in detection
    ColorDetector.persistanceColor(res)
  File "D:\Python projects\projet-i3-sneaker\src\blackBoxModules\colorDetector\ColorDetector.py", line 250, in persistanceColor
    deuxiemeElem = str([*keys][1])
IndexError: list index out of range

---------------------------------------
BlackBox-2 encountered an error, and stopped its execution. See the error below: 

---------------------------------------
Traceback (most recent call last):
  File "D:\Python projects\projet-i3-sneaker\src\BlackBox.py", line 80, in run
    self.compute(nextTask.img, nextTask.imgPath, nextTask.imgPathInCache, nextTask.tfImg, modelShoeDetector)
  File "D:\Python projects\projet-i3-sneaker\src\BlackBox.py", line 124, in compute
    (mainColor, secondaryColor) = ColorDetector.detection(
  File "D:\Python projects\projet-i3-sneaker\src\blackBoxModules\colorDetector\ColorDetector.py", line 321, in detection
    ColorDetector.persistanceColor(res)
  File "D:\Python projects\projet-i3-sneaker\src\blackBoxModules\colorDetector\ColorDetector.py", line 250, in persistanceColor
    deuxiemeElem = str([*keys][1])
IndexError: list index out of range

---------------------------------------
BlackBox-2 encountered an error, and stopped its execution. See the error below: 

---------------------------------------
Traceback (most recent call last):
  File "D:\Python projects\projet-i3-sneaker\src\BlackBox.py", line 80, in run
    self.compute(nextTask.img, nextTask.imgPath, nextTask.imgPathInCache, nextTask.tfImg, modelShoeDetector)
  File "D:\Python projects\projet-i3-sneaker\src\BlackBox.py", line 124, in compute
    (mainColor, secondaryColor) = ColorDetector.detection(
  File "D:\Python projects\projet-i3-sneaker\src\blackBoxModules\colorDetector\ColorDetector.py", line 323, in detection
    ColorDetector.persistanceColor(res)
  File "D:\Python projects\projet-i3-sneaker\src\blackBoxModules\colorDetector\ColorDetector.py", line 249, in persistanceColor
    if(len(keys == 2)):
TypeError: object of type 'bool' has no len()

---------------------------------------
No blackboxes are running. Politely stopping the program.
---------------------------------------
BlackBox-2 encountered an error, and stopped its execution. See the error below: 

---------------------------------------
Traceback (most recent call last):
  File "D:\Python projects\projet-i3-sneaker\src\BlackBox.py", line 80, in run
    self.compute(nextTask.img, nextTask.imgPath, nextTask.imgPathInCache, nextTask.tfImg, modelShoeDetector)
  File "D:\Python projects\projet-i3-sneaker\src\BlackBox.py", line 124, in compute
    (mainColor, secondaryColor) = ColorDetector.detection(
  File "D:\Python projects\projet-i3-sneaker\src\blackBoxModules\colorDetector\ColorDetector.py", line 323, in detection
    ColorDetector.persistanceColor(res)
  File "D:\Python projects\projet-i3-sneaker\src\blackBoxModules\colorDetector\ColorDetector.py", line 252, in persistanceColor
    deuxiemeElem = str([*keys][1])
IndexError: list index out of range

---------------------------------------
BlackBox-2 encountered an error, and stopped its execution. See the error below: 

---------------------------------------
Traceback (most recent call last):
  File "D:\Python projects\projet-i3-sneaker\src\BlackBox.py", line 80, in run
    self.compute(nextTask.img, nextTask.imgPath, nextTask.imgPathInCache, nextTask.tfImg, modelShoeDetector)
  File "D:\Python projects\projet-i3-sneaker\src\BlackBox.py", line 124, in compute
    (mainColor, secondaryColor) = ColorDetector.detection(
  File "D:\Python projects\projet-i3-sneaker\src\blackBoxModules\colorDetector\ColorDetector.py", line 323, in detection
    ColorDetector.persistanceColor(res)
  File "D:\Python projects\projet-i3-sneaker\src\blackBoxModules\colorDetector\ColorDetector.py", line 252, in persistanceColor
    deuxiemeElem = str([*keys][1])
IndexError: list index out of range

---------------------------------------
BlackBox-2 encountered an error, and stopped its execution. See the error below: 

---------------------------------------
Traceback (most recent call last):
  File "D:\Python projects\projet-i3-sneaker\src\BlackBox.py", line 80, in run
    self.compute(nextTask.img, nextTask.imgPath, nextTask.imgPathInCache, nextTask.tfImg, modelShoeDetector)
  File "D:\Python projects\projet-i3-sneaker\src\BlackBox.py", line 124, in compute
    (mainColor, secondaryColor) = ColorDetector.detection(
  File "D:\Python projects\projet-i3-sneaker\src\blackBoxModules\colorDetector\ColorDetector.py", line 323, in detection
    ColorDetector.persistanceColor(res)
  File "D:\Python projects\projet-i3-sneaker\src\blackBoxModules\colorDetector\ColorDetector.py", line 252, in persistanceColor
    deuxiemeElem = str([*keys][1])
IndexError: list index out of range

---------------------------------------
BlackBox-2 encountered an error, and stopped its execution. See the error below: 

---------------------------------------
Traceback (most recent call last):
  File "D:\Python projects\projet-i3-sneaker\src\BlackBox.py", line 80, in run
    self.compute(nextTask.img, nextTask.imgPath, nextTask.imgPathInCache, nextTask.tfImg, modelShoeDetector)
  File "D:\Python projects\projet-i3-sneaker\src\BlackBox.py", line 124, in compute
    (mainColor, secondaryColor) = ColorDetector.detection(
  File "D:\Python projects\projet-i3-sneaker\src\blackBoxModules\colorDetector\ColorDetector.py", line 326, in detection
    ColorDetector.persistanceColor(res)
  File "D:\Python projects\projet-i3-sneaker\src\blackBoxModules\colorDetector\ColorDetector.py", line 255, in persistanceColor
    deuxiemeElem = str([*keys][1])
IndexError: list index out of range

---------------------------------------
BlackBox-2 encountered an error, and stopped its execution. See the error below: 

---------------------------------------
Traceback (most recent call last):
  File "D:\Python projects\projet-i3-sneaker\src\BlackBox.py", line 80, in run
    self.compute(nextTask.img, nextTask.imgPath, nextTask.imgPathInCache, nextTask.tfImg, modelShoeDetector)
  File "D:\Python projects\projet-i3-sneaker\src\BlackBox.py", line 124, in compute
    (mainColor, secondaryColor) = ColorDetector.detection(
  File "D:\Python projects\projet-i3-sneaker\src\blackBoxModules\colorDetector\ColorDetector.py", line 323, in detection
    ColorDetector.persistanceColor(res)
  File "D:\Python projects\projet-i3-sneaker\src\blackBoxModules\colorDetector\ColorDetector.py", line 253, in persistanceColor
    if (dict[premierElem] != dict[deuxiemeElem]):
UnboundLocalError: local variable 'premierElem' referenced before assignment

---------------------------------------
BlackBox-2 encountered an error, and stopped its execution. See the error below: 

---------------------------------------
Traceback (most recent call last):
  File "C:\Users\Esteban\Documents\GitHub\projet-i3-sneaker\src\BlackBox.py", line 84, in run
    if ProcConfig.shouldReloadConfig():
  File "C:\Users\Esteban\Documents\GitHub\projet-i3-sneaker\src\utilities\configUtilities\ProcConfig.py", line 36, in shouldReloadConfig
    def shouldReloadConfig(): return ConfigLoader.getVariable('runConfig', 'dynamicConfig')
  File "C:\Users\Esteban\Documents\GitHub\projet-i3-sneaker\src\utilities\configUtilities\ConfigLoader.py", line 22, in getVariable
    raise ValueError('No such value in the config file: '+str(varPath)+"\n(failed at: "+str(varPath[i]))
ValueError: No such value in the config file: ('runConfig', 'dynamicConfig')
(failed at: dynamicConfig

---------------------------------------
BlackBox-3 encountered an error, and stopped its execution. See the error below: 

---------------------------------------
Traceback (most recent call last):
  File "C:\Users\Esteban\Documents\GitHub\projet-i3-sneaker\src\BlackBox.py", line 84, in run
    if ProcConfig.shouldReloadConfig():
  File "C:\Users\Esteban\Documents\GitHub\projet-i3-sneaker\src\utilities\configUtilities\ProcConfig.py", line 36, in shouldReloadConfig
    def shouldReloadConfig(): return ConfigLoader.getVariable('runConfig', 'dynamicConfig')
  File "C:\Users\Esteban\Documents\GitHub\projet-i3-sneaker\src\utilities\configUtilities\ConfigLoader.py", line 22, in getVariable
    raise ValueError('No such value in the config file: '+str(varPath)+"\n(failed at: "+str(varPath[i]))
ValueError: No such value in the config file: ('runConfig', 'dynamicConfig')
(failed at: dynamicConfig

---------------------------------------
A dev broke the basic skeletton of the BlackBox.
---------------------------------------
BlackBox-4 encountered an error, and stopped its execution. See the error below: 

---------------------------------------
Traceback (most recent call last):
  File "C:\Users\Esteban\Documents\GitHub\projet-i3-sneaker\src\BlackBox.py", line 82, in run
    self.taskQueue.task_done()    # helps when we want to join threads at the end of the programm
  File "C:\Users\Esteban\AppData\Local\Programs\Python\Python39\lib\multiprocessing\queues.py", line 325, in task_done
    raise ValueError('task_done() called too many times')
ValueError: task_done() called too many times

---------------------------------------
A dev broke the basic skeletton of the BlackBox.
---------------------------------------
BlackBox-5 encountered an error, and stopped its execution. See the error below: 

---------------------------------------
Traceback (most recent call last):
  File "C:\Users\Esteban\Documents\GitHub\projet-i3-sneaker\src\BlackBox.py", line 82, in run
    self.taskQueue.task_done()    # helps when we want to join threads at the end of the programm
  File "C:\Users\Esteban\AppData\Local\Programs\Python\Python39\lib\multiprocessing\queues.py", line 325, in task_done
    raise ValueError('task_done() called too many times')
ValueError: task_done() called too many times

---------------------------------------
BlackBox-2 encountered an error, and stopped its execution. See the error below: 

---------------------------------------
Traceback (most recent call last):
  File "C:\Users\Esteban\Documents\GitHub\projet-i3-sneaker\src\BlackBox.py", line 74, in run
    self.compute(nextTask.img, nextTask.imgPath, nextTask.imgPathInCache, nextTask.tfImg, modelShoeDetector)
  File "C:\Users\Esteban\Documents\GitHub\projet-i3-sneaker\src\BlackBox.py", line 113, in compute
    (mainColor, secondaryColor) = ColorDetector.detection(
  File "C:\Users\Esteban\Documents\GitHub\projet-i3-sneaker\src\blackBoxModules\colorDetector\ColorDetector.py", line 317, in detection
    list = ColorDetector.getDominantColors(image)
  File "C:\Users\Esteban\Documents\GitHub\projet-i3-sneaker\src\blackBoxModules\colorDetector\ColorDetector.py", line 110, in getDominantColors
    colors,counts = ColorDetector.detectColorsOf(imgPreproc)
  File "C:\Users\Esteban\Documents\GitHub\projet-i3-sneaker\src\blackBoxModules\colorDetector\ColorDetector.py", line 33, in detectColorsOf
    _, labels, palette = cv2.kmeans(pixels, n_colors, None, criteria, ConfigLoader.getVariable('color_detection','attempts'), flags)
NameError: name 'ConfigLoader' is not defined

---------------------------------------
BlackBox-2 encountered an error, and stopped its execution. See the error below: 

---------------------------------------
Traceback (most recent call last):
  File "C:\Users\Esteban\Documents\GitHub\projet-i3-sneaker\src\BlackBox.py", line 74, in run
    self.compute(nextTask.img, nextTask.imgPath, nextTask.imgPathInCache, nextTask.tfImg, modelShoeDetector)
  File "C:\Users\Esteban\Documents\GitHub\projet-i3-sneaker\src\BlackBox.py", line 113, in compute
    (mainColor, secondaryColor) = ColorDetector.detection(
  File "C:\Users\Esteban\Documents\GitHub\projet-i3-sneaker\src\blackBoxModules\colorDetector\ColorDetector.py", line 317, in detection
    list = ColorDetector.getDominantColors(image)
  File "C:\Users\Esteban\Documents\GitHub\projet-i3-sneaker\src\blackBoxModules\colorDetector\ColorDetector.py", line 108, in getDominantColors
    imagesNoBg = BackgroundSuppression.replaceBackground(image)
  File "C:\Users\Esteban\Documents\GitHub\projet-i3-sneaker\src\blackBoxModules\preprocess\BackgroundSuppression.py", line 70, in replaceBackground
    masked = (mask_stack * image) + ((1-mask_stack) * ast.literal_eval(__MASK_COLOR[key]))
  File "C:\Users\Esteban\AppData\Local\Programs\Python\Python39\lib\ast.py", line 105, in literal_eval
    return _convert(node_or_string)
  File "C:\Users\Esteban\AppData\Local\Programs\Python\Python39\lib\ast.py", line 104, in _convert
    return _convert_signed_num(node)
  File "C:\Users\Esteban\AppData\Local\Programs\Python\Python39\lib\ast.py", line 78, in _convert_signed_num
    return _convert_num(node)
  File "C:\Users\Esteban\AppData\Local\Programs\Python\Python39\lib\ast.py", line 69, in _convert_num
    _raise_malformed_node(node)
  File "C:\Users\Esteban\AppData\Local\Programs\Python\Python39\lib\ast.py", line 66, in _raise_malformed_node
    raise ValueError(f'malformed node or string: {node!r}')
ValueError: malformed node or string: [0.0, 1.0, 0.0]

---------------------------------------
BlackBox-2 encountered an error, and stopped its execution. See the error below: 

---------------------------------------
Traceback (most recent call last):
  File "C:\Users\Esteban\Documents\GitHub\projet-i3-sneaker\src\BlackBox.py", line 74, in run
    self.compute(nextTask.img, nextTask.imgPath, nextTask.imgPathInCache, nextTask.tfImg, modelShoeDetector)
  File "C:\Users\Esteban\Documents\GitHub\projet-i3-sneaker\src\BlackBox.py", line 113, in compute
    (mainColor, secondaryColor) = ColorDetector.detection(
  File "C:\Users\Esteban\Documents\GitHub\projet-i3-sneaker\src\blackBoxModules\colorDetector\ColorDetector.py", line 317, in detection
    list = ColorDetector.getDominantColors(image)
  File "C:\Users\Esteban\Documents\GitHub\projet-i3-sneaker\src\blackBoxModules\colorDetector\ColorDetector.py", line 108, in getDominantColors
    imagesNoBg = BackgroundSuppression.replaceBackground(image)
  File "C:\Users\Esteban\Documents\GitHub\projet-i3-sneaker\src\blackBoxModules\preprocess\BackgroundSuppression.py", line 70, in replaceBackground
    masked = (mask_stack * image) + ((1-mask_stack) * ast.literal_eval(__MASK_COLOR[key]))
  File "C:\Users\Esteban\AppData\Local\Programs\Python\Python39\lib\ast.py", line 105, in literal_eval
    return _convert(node_or_string)
  File "C:\Users\Esteban\AppData\Local\Programs\Python\Python39\lib\ast.py", line 104, in _convert
    return _convert_signed_num(node)
  File "C:\Users\Esteban\AppData\Local\Programs\Python\Python39\lib\ast.py", line 78, in _convert_signed_num
    return _convert_num(node)
  File "C:\Users\Esteban\AppData\Local\Programs\Python\Python39\lib\ast.py", line 69, in _convert_num
    _raise_malformed_node(node)
  File "C:\Users\Esteban\AppData\Local\Programs\Python\Python39\lib\ast.py", line 66, in _raise_malformed_node
    raise ValueError(f'malformed node or string: {node!r}')
ValueError: malformed node or string: [0.0, 1.0, 0.0]

---------------------------------------
BlackBox-2 encountered an error, and stopped its execution. See the error below: 

---------------------------------------
Traceback (most recent call last):
  File "C:\Users\Esteban\Documents\GitHub\projet-i3-sneaker\src\BlackBox.py", line 74, in run
    self.compute(nextTask.img, nextTask.imgPath, nextTask.imgPathInCache, nextTask.tfImg, modelShoeDetector)
  File "C:\Users\Esteban\Documents\GitHub\projet-i3-sneaker\src\BlackBox.py", line 113, in compute
    (mainColor, secondaryColor) = ColorDetector.detection(
  File "C:\Users\Esteban\Documents\GitHub\projet-i3-sneaker\src\blackBoxModules\colorDetector\ColorDetector.py", line 317, in detection
    list = ColorDetector.getDominantColors(image)
  File "C:\Users\Esteban\Documents\GitHub\projet-i3-sneaker\src\blackBoxModules\colorDetector\ColorDetector.py", line 108, in getDominantColors
    imagesNoBg = BackgroundSuppression.replaceBackground(image)
  File "C:\Users\Esteban\Documents\GitHub\projet-i3-sneaker\src\blackBoxModules\preprocess\BackgroundSuppression.py", line 70, in replaceBackground
    masked = (mask_stack * image) + ((1-mask_stack) * ast.literal_eval(__MASK_COLOR[key]))
  File "C:\Users\Esteban\AppData\Local\Programs\Python\Python39\lib\ast.py", line 105, in literal_eval
    return _convert(node_or_string)
  File "C:\Users\Esteban\AppData\Local\Programs\Python\Python39\lib\ast.py", line 104, in _convert
    return _convert_signed_num(node)
  File "C:\Users\Esteban\AppData\Local\Programs\Python\Python39\lib\ast.py", line 78, in _convert_signed_num
    return _convert_num(node)
  File "C:\Users\Esteban\AppData\Local\Programs\Python\Python39\lib\ast.py", line 69, in _convert_num
    _raise_malformed_node(node)
  File "C:\Users\Esteban\AppData\Local\Programs\Python\Python39\lib\ast.py", line 66, in _raise_malformed_node
    raise ValueError(f'malformed node or string: {node!r}')
ValueError: malformed node or string: [0.0, 1.0, 0.0]

---------------------------------------
BlackBox-2 encountered an error, and stopped its execution. See the error below: 

---------------------------------------
Traceback (most recent call last):
  File "C:\Users\Esteban\Documents\GitHub\projet-i3-sneaker\src\BlackBox.py", line 74, in run
    self.compute(nextTask.img, nextTask.imgPath, nextTask.imgPathInCache, nextTask.tfImg, modelShoeDetector)
  File "C:\Users\Esteban\Documents\GitHub\projet-i3-sneaker\src\BlackBox.py", line 113, in compute
    (mainColor, secondaryColor) = ColorDetector.detection(
  File "C:\Users\Esteban\Documents\GitHub\projet-i3-sneaker\src\blackBoxModules\colorDetector\ColorDetector.py", line 318, in detection
    list = ColorDetector.deleteBackground(list)
  File "C:\Users\Esteban\Documents\GitHub\projet-i3-sneaker\src\blackBoxModules\colorDetector\ColorDetector.py", line 125, in deleteBackground
    listColorBg = ColorDetector.getBackgroundColors('color')
  File "C:\Users\Esteban\Documents\GitHub\projet-i3-sneaker\src\blackBoxModules\colorDetector\ColorDetector.py", line 296, in getBackgroundColors
    newColor = Color(rgb=[(elem * 255) for elem in listColor])
  File "C:\Users\Esteban\Documents\GitHub\projet-i3-sneaker\src\Data\Color.py", line 40, in __init__
    decidedC = ColorEnum.getClosestColorByRGB(rgb[0],rgb[1], rgb[2])
  File "C:\Users\Esteban\Documents\GitHub\projet-i3-sneaker\src\Data\BasicColors.py", line 92, in getClosestColorByRGB
    difRc = abs(rc-r)/255.0
TypeError: unsupported operand type(s) for -: 'int' and 'str'

---------------------------------------
BlackBox-2 encountered an error, and stopped its execution. See the error below: 

---------------------------------------
Traceback (most recent call last):
  File "C:\Users\Esteban\Documents\GitHub\projet-i3-sneaker\src\BlackBox.py", line 74, in run
    self.compute(nextTask.img, nextTask.imgPath, nextTask.imgPathInCache, nextTask.tfImg, modelShoeDetector)
  File "C:\Users\Esteban\Documents\GitHub\projet-i3-sneaker\src\BlackBox.py", line 113, in compute
    (mainColor, secondaryColor) = ColorDetector.detection(
  File "C:\Users\Esteban\Documents\GitHub\projet-i3-sneaker\src\blackBoxModules\colorDetector\ColorDetector.py", line 317, in detection
    list = ColorDetector.getDominantColors(image)
  File "C:\Users\Esteban\Documents\GitHub\projet-i3-sneaker\src\blackBoxModules\colorDetector\ColorDetector.py", line 108, in getDominantColors
    imagesNoBg = BackgroundSuppression.replaceBackground(image)
  File "C:\Users\Esteban\Documents\GitHub\projet-i3-sneaker\src\blackBoxModules\preprocess\BackgroundSuppression.py", line 71, in replaceBackground
    masked = (mask_stack * image) + ((1-mask_stack) * ast.literal_eval(__MASK_COLOR[key]))
  File "C:\Users\Esteban\AppData\Local\Programs\Python\Python39\lib\ast.py", line 105, in literal_eval
    return _convert(node_or_string)
  File "C:\Users\Esteban\AppData\Local\Programs\Python\Python39\lib\ast.py", line 104, in _convert
    return _convert_signed_num(node)
  File "C:\Users\Esteban\AppData\Local\Programs\Python\Python39\lib\ast.py", line 78, in _convert_signed_num
    return _convert_num(node)
  File "C:\Users\Esteban\AppData\Local\Programs\Python\Python39\lib\ast.py", line 69, in _convert_num
    _raise_malformed_node(node)
  File "C:\Users\Esteban\AppData\Local\Programs\Python\Python39\lib\ast.py", line 66, in _raise_malformed_node
    raise ValueError(f'malformed node or string: {node!r}')
ValueError: malformed node or string: [0.0, 1.0, 0.0]

---------------------------------------
BlackBox-2 encountered an error, and stopped its execution. See the error below: 

---------------------------------------
Traceback (most recent call last):
  File "C:\Users\Esteban\Documents\GitHub\projet-i3-sneaker\src\BlackBox.py", line 74, in run
    self.compute(nextTask.img, nextTask.imgPath, nextTask.imgPathInCache, nextTask.tfImg, modelShoeDetector)
  File "C:\Users\Esteban\Documents\GitHub\projet-i3-sneaker\src\BlackBox.py", line 113, in compute
    (mainColor, secondaryColor) = ColorDetector.detection(
  File "C:\Users\Esteban\Documents\GitHub\projet-i3-sneaker\src\blackBoxModules\colorDetector\ColorDetector.py", line 317, in detection
    list = ColorDetector.getDominantColors(image)
  File "C:\Users\Esteban\Documents\GitHub\projet-i3-sneaker\src\blackBoxModules\colorDetector\ColorDetector.py", line 108, in getDominantColors
    imagesNoBg = BackgroundSuppression.replaceBackground(image)
  File "C:\Users\Esteban\Documents\GitHub\projet-i3-sneaker\src\blackBoxModules\preprocess\BackgroundSuppression.py", line 72, in replaceBackground
    masked = (mask_stack * image) + ((1-mask_stack) * ast.literal_eval(__MASK_COLOR[key]))
  File "C:\Users\Esteban\AppData\Local\Programs\Python\Python39\lib\ast.py", line 105, in literal_eval
    return _convert(node_or_string)
  File "C:\Users\Esteban\AppData\Local\Programs\Python\Python39\lib\ast.py", line 104, in _convert
    return _convert_signed_num(node)
  File "C:\Users\Esteban\AppData\Local\Programs\Python\Python39\lib\ast.py", line 78, in _convert_signed_num
    return _convert_num(node)
  File "C:\Users\Esteban\AppData\Local\Programs\Python\Python39\lib\ast.py", line 69, in _convert_num
    _raise_malformed_node(node)
  File "C:\Users\Esteban\AppData\Local\Programs\Python\Python39\lib\ast.py", line 66, in _raise_malformed_node
    raise ValueError(f'malformed node or string: {node!r}')
ValueError: malformed node or string: [0.0, 1.0, 0.0]

---------------------------------------
BlackBox-2 encountered an error, and stopped its execution. See the error below: 

---------------------------------------
Traceback (most recent call last):
  File "C:\Users\Esteban\Documents\GitHub\projet-i3-sneaker\src\BlackBox.py", line 74, in run
    self.compute(nextTask.img, nextTask.imgPath, nextTask.imgPathInCache, nextTask.tfImg, modelShoeDetector)
  File "C:\Users\Esteban\Documents\GitHub\projet-i3-sneaker\src\BlackBox.py", line 113, in compute
    (mainColor, secondaryColor) = ColorDetector.detection(
  File "C:\Users\Esteban\Documents\GitHub\projet-i3-sneaker\src\blackBoxModules\colorDetector\ColorDetector.py", line 318, in detection
    list = ColorDetector.deleteBackground(list)
  File "C:\Users\Esteban\Documents\GitHub\projet-i3-sneaker\src\blackBoxModules\colorDetector\ColorDetector.py", line 125, in deleteBackground
    listColorBg = ColorDetector.getBackgroundColors('color')
  File "C:\Users\Esteban\Documents\GitHub\projet-i3-sneaker\src\blackBoxModules\colorDetector\ColorDetector.py", line 296, in getBackgroundColors
    newColor = Color(rgb=[(elem * 255) for elem in listColor])
  File "C:\Users\Esteban\Documents\GitHub\projet-i3-sneaker\src\Data\Color.py", line 40, in __init__
    decidedC = ColorEnum.getClosestColorByRGB(rgb[0],rgb[1], rgb[2])
  File "C:\Users\Esteban\Documents\GitHub\projet-i3-sneaker\src\Data\BasicColors.py", line 92, in getClosestColorByRGB
    difRc = abs(rc-r)/255.0
TypeError: unsupported operand type(s) for -: 'int' and 'str'

---------------------------------------
BlackBox-2 encountered an error, and stopped its execution. See the error below: 

---------------------------------------
Traceback (most recent call last):
  File "C:\Users\Esteban\Documents\GitHub\projet-i3-sneaker\src\BlackBox.py", line 74, in run
    self.compute(nextTask.img, nextTask.imgPath, nextTask.imgPathInCache, nextTask.tfImg, modelShoeDetector)
  File "C:\Users\Esteban\Documents\GitHub\projet-i3-sneaker\src\BlackBox.py", line 113, in compute
    (mainColor, secondaryColor) = ColorDetector.detection(
  File "C:\Users\Esteban\Documents\GitHub\projet-i3-sneaker\src\blackBoxModules\colorDetector\ColorDetector.py", line 319, in detection
    list = ColorDetector.deleteBackground(list)
  File "C:\Users\Esteban\Documents\GitHub\projet-i3-sneaker\src\blackBoxModules\colorDetector\ColorDetector.py", line 125, in deleteBackground
    listColorBg = ColorDetector.getBackgroundColors('color')
  File "C:\Users\Esteban\Documents\GitHub\projet-i3-sneaker\src\blackBoxModules\colorDetector\ColorDetector.py", line 297, in getBackgroundColors
    newColor = Color(rgb=[(elem * 255) for elem in listColor])
  File "C:\Users\Esteban\Documents\GitHub\projet-i3-sneaker\src\Data\Color.py", line 40, in __init__
    decidedC = ColorEnum.getClosestColorByRGB(rgb[0],rgb[1], rgb[2])
  File "C:\Users\Esteban\Documents\GitHub\projet-i3-sneaker\src\Data\BasicColors.py", line 93, in getClosestColorByRGB
    difRc = abs(rc-r)/255.0
TypeError: unsupported operand type(s) for -: 'int' and 'str'
